steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/sec-scanner:$COMMIT_SHA
      - .

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/sec-scanner:$COMMIT_SHA

  # Deploy to Cloud Run (env vars already set on the service, no need to repeat them)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - sec-scanner
      - --image
      - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/sec-scanner:$COMMIT_SHA
      - --region
      - europe-west1
      - --allow-unauthenticated
      - --min-instances
      - '1'

images:
  - europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/sec-scanner:$COMMIT_SHA
